version: '2'

networks:
  app-tier:
    driver: bridge

services:
  nats:
    image: 'bitnami/nats:latest'
    ports:
      - 4222:4222 # client port
      - 6222:6222 # cluster port
      - 8222:8222 # monitoring port
    networks:
      - app-tier
